### ISSUE TITLE
Create an overview diagram! Just like mix what is important!

### ISSUE THREAD

**Issue by Gustavwk** [johannesmols/Caelicus#26]
input/output? How is stuff calculated? Capture the idea!!

**Comment by jaschn** [comment]
![MBSE](https://user-images.githubusercontent.com/49870201/97887302-008cee00-1d2a-11eb-8734-e0fb632a842b.png)

**Comment by jaschn** [comment]
[MBSE.zip](https://github.com/johannesmols/Caelicus/files/5476706/MBSE.zip)
![MBSE](https://user-images.githubusercontent.com/49870201/97897091-4780e080-1d36-11eb-851b-ffe0301abdcd.png)
