### ISSUE TITLE
Start Working in UnitTests

### ISSUE THREAD

**Issue by Gustavwk** [johannesmols/Caelicus#34]

**Comment by parzival3** [comment]
- Simulation​

   - [ ] Vehicles and orders are evenly distributed among all base stations​

   - [ ] Vehicles can find the shortest path to a target​

   - [ ] Vehicles can claim an order and deliver it using that shortest path​

   - [ ] Vehicles can find the nearest order after a successful delivery and travel there​

   - [ ] Vehicles idle at the current base station if there are no open orders available​

   - [ ] Simulation events are correctly logged​

   - [ ] Simulation results are correctly recorded​

- SimulationManager​

  - [ ]  Multiple simulations can be added​

  - [ ]  The simluations can be started and stopped​

  - [ ]  The results of a simulation is saved in the local storage of the browser or in a file​

- GraphImporterService​

  - [ ] Can correctly convert a graph from JSON representation to a C# class instance​

  - [ ] All vertices have their correct parameters (e.g. position, name, …)​

  - [ ] All edges between vertices are correctly added (both ways)​

​

**Comment by parzival3** [comment]
> - [ ]  The results of a simulation is saved in the local storage of the browser or in a file​

@johannesmols  can we currently test this?

**Comment by johannesmols** [comment]
@parzival3 Yes I added functionality yesterday that records each step in the simulation in an object. If you try and run the latest version there is a download button where it will zip all simulation results and download to your computer.

**Comment by parzival3** [comment]
@johannesmols Oh haven't noticed that this moring :+1: I'll add a test later today thanks :+1:
