### ISSUE TITLE
Diagram based on parameters (Brainstorming)

### ISSUE THREAD

**Issue by Gustavwk** [johannesmols/Caelicus#43]

**Comment by jaschn** [comment]
![Folie3](https://user-images.githubusercontent.com/49870201/99409997-3fa66c00-28f2-11eb-8eee-e25a5e875a52.JPG)
![Folie1](https://user-images.githubusercontent.com/49870201/99410001-403f0280-28f2-11eb-899c-161172d4a821.JPG)
![Folie2](https://user-images.githubusercontent.com/49870201/99410003-403f0280-28f2-11eb-9c10-09947cb93aad.JPG)

**Comment by jaschn** [comment]
Hi @johannesmols i added the first two Diagrams. A few things we still have to consider.
-The Distance and Time of Orders does not get set. (I only added that, before you made changes to the simulation)
-The Diagrams need all Simulations. With the upload on the result page only one simulation can be uploaded. I didn't get uploading a zip file to work :/. This means that currently the simulations are only stored in the Appstate and used for the Diagrams.
